const currentYear = new Date().getFullYear()
export const classProgression: Record<string, string> = {
  'Creche': 'Reception',
  'Reception': 'Pre School',
  'Pre School': 'Pre KG',
  'Pre KG': 'KG',
  'KG': 'Grade 1',
  'Grade 1': 'Grade 2',
  'Grade 2': 'Grade 3',
  'Grade 3': 'Grade 4',
  'Grade 4': 'Grade 5',
  'Grade 5': 'JSS 1',
  'JSS 1': 'JSS 2',
  'JSS 2': 'JSS 3',
  'JSS 3': 'SSS 1',
  'SSS 1': 'SSS 2',
  'SSS 2': 'SSS 3',
  'SSS 3': `${currentYear} Graduate`,
};

export const classCodeMapping: Record<string, string> = {
  'Creche': 'CR',
  'Reception': 'RP',
  'Pre School': 'PS',
  'Pre KG': 'PKG',
  'KG': 'KG',
  'Grade 1': 'G1',
  'Grade 2': 'G2',
  'Grade 3': 'G3',
  'Grade 4': 'G4',
  'Grade 5': 'G5',
  'Grade 6': 'G6',
  'JSS 1': 'J1',
  'JSS 2': 'J2',
  'JSS 3': 'J3',
  'SSS 1': 'S1',
  'SSS 2': 'S2',
  'SSS 3': 'S3',
};

export const levels: string[] = [
  'Creche',
  'Reception',
  'Pre School',
  'Pre KG',
  'KG',
  'Grade 1',
  'Grade 2',
  'Grade 3',
  'Grade 4',
  'Grade 5',
  'JSS 1',
  'JSS 2',
  'JSS 3',
  'SSS 1',
  'SSS 2',
  'SSS 3',
];
